"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Search, House, Film, Clapperboard, Sparkles, BookOpen, Library, Layers3, Play, Plus, Check, ChevronLeft, ChevronRight, PanelLeftClose, Menu, X, ExternalLink, LoaderCircle, TvMinimal, CircleAlert } from "lucide-react";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import MediaPlayer from "@/components/media-player";
import MangaReader from "@/components/manga-reader";
import { directory } from "@/lib/directory";
import { providers as apiProviders, mergeWorks, mangaSources, type Work, type Source, type ProviderStatus } from "@/lib/media";
import {siteProviders} from "@/lib/site-provider-info";
import hotSnapshot from "@/lib/hot-snapshot.json";
import { artwork, kindNames, readLocal, writeLocal, saveProgress, type Progress } from "@/lib/experience";
type View="home"|"search"|"movie"|"tv"|"anime"|"manga"|"library"|"sources"|"detail";
type Route={view:View;q:string;kind:string;key?:string};
type Results={works:Work[];statuses:ProviderStatus[];page:number};
const providers=[...apiProviders,...siteProviders];
const navigation=[{id:"home",label:"主页",icon:House},{id:"movie",label:"电影",icon:Film},{id:"tv",label:"电视剧",icon:Clapperboard},{id:"anime",label:"动画",icon:Sparkles},{id:"manga",label:"漫画",icon:BookOpen},{id:"library",label:"资料库",icon:Library}];
const regions:Record<string,RegExp>={cn:/中国|大陆|香港|台湾|华语/,us:/美国/,eu:/英国|法国|德国|意大利|西班牙|欧洲|瑞典|丹麦|挪威|芬兰|俄罗斯|波兰|荷兰|爱尔兰/,jp:/日本|^ja$/,kr:/韩国|^ko$/,in:/印度/};
function sourceKey(s:Source){return s.provider+":"+s.id;}
function preferredSource(sources:Source[],saved?:string){return sources.find(s=>sourceKey(s)===saved)||sources.find(s=>s.provider===saved)||sources[0];}
function parseRoute():Route{const p=new URLSearchParams(location.hash.slice(1));const k=p.get("kind")||"all",q=p.get("q")||"",v=p.get("view");return {view:(["home","search","movie","tv","anime","manga","library","sources","detail"].includes(v||"")?v:q?"search":["movie","tv","anime","manga"].includes(k)?k:"home") as View,q,kind:k in kindNames?k:"all",key:p.get("work")||undefined};}
export default function Home(){
 const [popular,setPopular]=useState(hotSnapshot as {movie:Work[];tv:Work[];anime:Work[];updatedAt:string});
 const [route,setRoute]=useState<Route>({view:"home",q:"",kind:"all"}),[query,setQuery]=useState(""),[results,setResults]=useState<Results>({works:[],statuses:[],page:1}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState<Work|null>(null),[region,setRegion]=useState("all"),[collapsed,setCollapsed]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[saved,setSaved]=useState<Work[]>([]),[progress,setProgress]=useState<Progress[]>([]),[recents,setRecents]=useState<string[]>([]);
 const regionRef=useRef(region);regionRef.current=region;
 const cache=useRef(new Map<string,Results>()),known=useRef(new Map([...hotSnapshot.movie,...hotSnapshot.tv,...hotSnapshot.anime].map(w=>[w.key,w as Work]))),request=useRef(0),abort=useRef<AbortController|null>(null),returnRoute=useRef<Route>({view:"home",q:"",kind:"all"}),returnScroll=useRef(0),returnFocus=useRef(""),searchInput=useRef<HTMLInputElement>(null);
 const loadResults=useCallback(async(q:string,kind:string,page=1,append=false)=>{
  const cacheKey=q+"|"+kind;
  const n=++request.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;setError("");
  const existing=cache.current.get(cacheKey);
  if(!append&&existing){setResults(existing);setBusy(false);return existing.works;}
  setBusy(true);if(!append)setResults({works:[],statuses:[],page:1});
  try{const r=await fetch("/api/search?q="+encodeURIComponent(q)+"&kind="+kind+"&page="+page,{signal:controller.signal});const d=await r.json() as Results&{error?:string};if(!r.ok||d.error)throw new Error(d.error||"暂时无法读取作品");if(n!==request.current)return [];
   const value={works:append?mergeWorks([...(existing?.works||[]),...d.works]):d.works,statuses:d.statuses||[],page};value.works.forEach(w=>known.current.set(w.key,w));cache.current.set(cacheKey,value);if(cache.current.size>12)cache.current.delete(cache.current.keys().next().value!);setResults(value);return value.works;
  }catch(e){if(n===request.current&&!(e instanceof Error&&e.name==="AbortError"))setError(e instanceof Error?e.message:"读取失败，请重试");return [];}finally{if(n===request.current)setBusy(false);}
 },[]);
 const navigate=useCallback((next:Route,replace=false)=>{
  const p=new URLSearchParams({view:next.view,kind:next.kind});if(next.q)p.set("q",next.q);if(next.key)p.set("work",next.key);
  history.replaceState({...history.state,scrollY:window.scrollY,region:regionRef.current},"");history[replace?"replaceState":"pushState"]({yingji:true,fromApp:!replace,scrollY:0},"","#"+p.toString());setRoute(next);setQuery(next.q);setMobileOpen(false);setRegion("all");window.scrollTo({top:0,behavior:"instant"});
 },[]);
 useEffect(()=>{const update=()=>{const r=parseRoute();setRoute(r);setQuery(r.q);setMobileOpen(false);setRegion(history.state?.region||"all");const y=history.state?.scrollY||0,key=history.state?.focusKey;setTimeout(()=>{window.scrollTo({top:y,behavior:"instant"});if(key)document.querySelector<HTMLElement>('[data-work-key="'+CSS.escape(key)+'"]')?.focus({preventScroll:true});},100);};const restoration=history.scrollRestoration;history.scrollRestoration="manual";update();window.addEventListener("popstate",update);return()=>{window.removeEventListener("popstate",update);history.scrollRestoration=restoration;abort.current?.abort();};},[]);
 useEffect(()=>{const update=()=>{const s=readLocal<Work[]>("saved",[]),p=readLocal<Progress[]>("progress",[]),r=readLocal<string[]>("searches",[]);setSaved(Array.isArray(s)?s:[]);setProgress(Array.isArray(p)?p:[]);setRecents(Array.isArray(r)?r:[]);};update();window.addEventListener("yingji-library",update);window.addEventListener("storage",update);return()=>{window.removeEventListener("yingji-library",update);window.removeEventListener("storage",update);};},[]);
 useEffect(()=>{let alive=true;const refresh=()=>fetch("/api/discover").then(r=>r.json() as Promise<{movie:Work[];tv:Work[];anime:Work[];updatedAt:string}>).then(d=>{if(alive&&d.movie?.length&&d.tv?.length&&d.anime?.length){setPopular(d);[...d.movie,...d.tv,...d.anime].forEach(w=>known.current.set(w.key,w));}}).catch(()=>{});void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh();},600_000);return()=>{alive=false;clearInterval(timer);};},[]);
 useEffect(()=>{
  if(route.view==="detail"){
   const knownWork=known.current.get(route.key||"");if(knownWork){setSelected(knownWork);return;}
   let active=true;setSelected(null);void loadResults(route.q,route.kind).then(items=>{if(active)setSelected(items.find(w=>w.key===route.key)||items.find(w=>w.title===route.q)||null);});return()=>{active=false;};
  }
  setSelected(null);
  if(!route.q&&route.kind!=="manga"){abort.current?.abort();++request.current;const items=route.kind==="all"?[...popular.movie.slice(0,8),...popular.tv.slice(0,8),...popular.anime.slice(0,8)]:popular[route.kind as "movie"|"tv"|"anime"]||[];setResults({works:items,statuses:[],page:1});setBusy(false);setError("");}
  else if(route.view==="search"||["movie","tv","anime","manga"].includes(route.view))void loadResults(route.q,route.kind);
  if(route.view==="search"&&!route.q)searchInput.current?.focus();
 },[route,loadResults,popular]);
 useEffect(()=>{function shortcuts(e:KeyboardEvent){const target=e.target as HTMLElement;if(target.closest("input,textarea,[contenteditable=true]"))return;if(e.key==="/"&&!document.fullscreenElement){e.preventDefault();navigate({view:"search",q:"",kind:"all"});}if(e.key==="Escape")setMobileOpen(false);}window.addEventListener("keydown",shortcuts);return()=>window.removeEventListener("keydown",shortcuts);},[navigate]);
 function search(q:string,kind=route.kind){q=q.trim();cache.current.delete(q+"|"+kind);navigate({view:"search",q,kind});if(q)writeLocal("searches",[q,...recents.filter(v=>v!==q)].slice(0,8));}
 function openWork(w:Work){known.current.set(w.key,w);returnRoute.current=route;returnScroll.current=window.scrollY;returnFocus.current=w.key;history.replaceState({...history.state,focusKey:w.key},"");navigate({view:"detail",q:w.title,kind:w.kind,key:w.key});}
 function back(){if(history.state?.fromApp){history.back();return;}navigate(returnRoute.current,true);setTimeout(()=>{window.scrollTo({top:returnScroll.current,behavior:"instant"});document.querySelector<HTMLElement>('[data-work-key="'+CSS.escape(returnFocus.current)+'"]')?.focus({preventScroll:true});},80);}
 function toggleSaved(w:Work){writeLocal("saved",saved.some(s=>s.key===w.key)?saved.filter(s=>s.key!==w.key):[w,...saved]);}
 useEffect(()=>{
  const context=(document as Document&{modelContext?:{registerTool:(t:any,o?:any)=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();
  const tools=[{name:"search_media",title:"搜索影视漫画",description:"搜索作品并更新结果。",inputSchema:{type:"object",properties:{query:{type:"string",minLength:1,maxLength:120},category:{type:"string",enum:Object.keys(kindNames)}},required:["query"],additionalProperties:false},async execute(i:any){if(typeof i.query!=="string"||!i.query.trim()||i.query.length>120||i.category&&!(i.category in kindNames))throw new Error("无效搜索");const kind=i.category||"all";const items=await loadResults(i.query.trim(),kind);navigate({view:"search",q:i.query.trim(),kind});return items.map(w=>({key:w.key,title:w.title,year:w.year,category:w.kind,sources:w.kind==="manga"?mangaSources(w).length:w.sources.length}));}},{name:"open_media_detail",title:"打开作品分流",description:"打开当前结果中作品的详情。",inputSchema:{type:"object",properties:{key:{type:"string"}},required:["key"],additionalProperties:false},execute(i:any){const w=known.current.get(i.key);if(!w)throw new Error("请先搜索作品");openWork(w);return {title:w.title,sources:w.kind==="manga"?mangaSources(w).map(s=>s.name):w.sources.map(s=>s.providerName)};}}];
  tools.forEach(t=>{try{void Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}});return()=>lifecycle.abort();
 },[navigate,loadResults,route]);
 const shown=results.works.filter(w=>region==="all"||regions[region]?.test(w.area));
 const category=kindNames[route.view],isHome=route.view==="home";
 return <div className={"app-shell"+(collapsed?" sidebar-collapsed":"")+(mobileOpen?" mobile-open":"")}>
  <button className="skip-link" onClick={()=>document.getElementById("main")?.focus()}>跳到内容</button>
  {mobileOpen&&<button className="nav-scrim" aria-label="关闭导航" onClick={()=>setMobileOpen(false)}/>}
  <aside className="sidebar" aria-label="主导航">
   <button className="profile" onClick={()=>navigate({view:"library",q:"",kind:"all"})}><span className="avatar">咚</span><span className="nav-label"><strong>我的片库</strong></span><ChevronRight className="profile-chevron" size={15}/></button>
   <button className={"nav-item search-nav"+(route.view==="search"?" active":"")} onClick={()=>navigate({view:"search",q:"",kind:"all"})} title="搜索"><Search/><span className="nav-label">搜索</span></button>
   <nav>{navigation.map(({id,label,icon:Icon})=><button key={id} className={"nav-item"+(route.view===id?" active":"")} aria-current={route.view===id?"page":undefined} title={label} onClick={()=>navigate({view:id as View,q:"",kind:id in kindNames?id:"all"})}><Icon/><span className="nav-label">{label}</span></button>)}</nav>
   <div className="sidebar-bottom"><button className={"nav-item"+(route.view==="sources"?" active":"")} title="全部来源" onClick={()=>navigate({view:"sources",q:"",kind:"all"})}><Layers3/><span className="nav-label">全部来源</span></button><button className="collapse-button" aria-label={collapsed?"展开侧栏":"收起侧栏"} onClick={()=>setCollapsed(!collapsed)}><PanelLeftClose size={19}/><span className="nav-label">收起侧栏</span></button></div>
  </aside>
  <header className="topbar"><div><button className="mobile-menu icon-button" aria-label="打开导航" onClick={()=>setMobileOpen(!mobileOpen)}><Menu/></button><button className="brand" onClick={()=>navigate({view:"home",q:"",kind:"all"})}><TvMinimal size={26}/><span>咚咚映画</span></button></div><div><button className="icon-button" aria-label="搜索作品" onClick={()=>navigate({view:"search",q:"",kind:"all"})}><Search size={21}/></button><button className="mini-avatar" aria-label="打开资料库" onClick={()=>navigate({view:"library",q:"",kind:"all"})}>咚</button></div></header>
  <main id="main" tabIndex={-1} className="main-content">
  <div className="view-enter" key={route.view==="search"?"search":route.view+(route.key||"")}>
  {isHome?<><HeroCarousel works={[...popular.movie,...popular.tv,...popular.anime].filter(w=>w.backdrop)} onOpen={openWork} saved={saved} onSave={toggleSaved}/>
   <div className="home-shelves">
    {progress.length>0&&<Shelf title="继续观看" works={progress.map(p=>p.work)} onOpen={openWork} progress={progress}/>}
    <Shelf title="电影热播" works={popular.movie.slice(0,18)} onOpen={openWork} onMore={()=>navigate({view:"movie",q:"",kind:"movie"})}/>
    <Shelf title="剧集热播" works={popular.tv.slice(0,18)} onOpen={openWork} onMore={()=>navigate({view:"tv",q:"",kind:"tv"})}/>
    <Shelf title="动画热播" works={popular.anime.slice(0,18)} onOpen={openWork} onMore={()=>navigate({view:"anime",q:"",kind:"anime"})}/>
   </div></>:route.view==="detail"?selected?<Detail work={selected} onBack={back} saved={saved.some(w=>w.key===selected.key)} onSave={()=>toggleSaved(selected)} resume={progress.find(p=>p.work.key===selected.key)}/>:<div className="page-content"><button className="back-button" onClick={back}><ChevronLeft/>返回</button>{busy?<Loading/>:<Empty title="暂时无法打开这部作品" note={error||"请重新搜索片名，查看可用来源。"} action={()=>search(route.q,route.kind)} actionLabel="重新搜索"/>}</div>:route.view==="library"?<div className="page-content"><PageHeading title="资料库"/>{progress.length>0&&<Shelf title="继续观看" works={progress.map(p=>p.work)} progress={progress} onOpen={openWork}/>}<div className="section-heading"><h2>待看清单</h2><span>{saved.length} 部作品</span></div>{saved.length?<div className="media-grid">{saved.map(w=><Card key={w.key} work={w} onOpen={openWork}/>)}</div>:<Empty title="暂无待看" action={()=>navigate({view:"home",q:"",kind:"all"})} actionLabel="探索作品"/>}</div>:route.view==="sources"?<div className="page-content"><PageHeading title="全部来源"/><div className="section-heading"><h2>统一搜索</h2><span>{providers.length} 个影视来源</span></div><div className="provider-inventory">{providers.map(p=>{const s=results.statuses.find(s=>s.id===p.id);return <div key={p.id}><span className="source-symbol"><Layers3 size={20}/></span><div><strong>{p.name}</strong><small>{s?s.state==="ok"?"可用":"暂不可用":""}</small></div></div>;})}</div><ExternalEntries kind="all" query={query}/></div>:<div className="page-content catalogue">
    <PageHeading title={route.view==="search"?"搜索":category||"探索"}/>
    <form className="search-box" role="search" onSubmit={e=>{e.preventDefault();search(query);}}><Search size={23}/><input ref={searchInput} aria-label="搜索片名或漫画" maxLength={120} value={query} onChange={e=>setQuery(e.target.value)} placeholder={route.view==="search"?"搜索片名、剧集或漫画":"搜索"+(category||"作品")}/>{query&&<button type="button" className="icon-button" aria-label="清空搜索" onClick={()=>{setQuery("");searchInput.current?.focus();}}><X size={19}/></button>}<button className="search-submit" type="submit" aria-label="搜索">{busy?<LoaderCircle className="spinning" size={19}/>:"搜索"}</button></form>
    {route.view==="search"&&!route.q&&<div className="recent-searches"><h2>{recents.length?"最近搜索":"热门搜索"}</h2><div>{(recents.length?recents:[popular.movie[0]?.title,popular.tv[0]?.title,popular.anime[0]?.title].filter(Boolean)).map(q=><button key={q} onClick={()=>search(q)}><Search size={15}/>{q}</button>)}</div></div>}
    <Tabs value={route.kind} onValueChange={k=>{setRegion("all");navigate({view:route.view==="search"?"search":k==="all"?"search":k as View,q:route.q,kind:k});}} className="category-tabs"><TabsList>{Object.entries(kindNames).map(([id,name])=><TabsTrigger key={id} value={id}>{name}</TabsTrigger>)}</TabsList></Tabs>
    <div className="section-heading result-heading"><div><h2>{route.q?"“"+route.q+"”":route.view==="manga"?"漫画":"热播"}</h2><p aria-live="polite">{busy?"正在查找作品…":shown.length+" 部作品"}</p></div><Select value={region} onValueChange={setRegion}><SelectTrigger aria-label="国家地区"><SelectValue/></SelectTrigger><SelectContent>{[["all","全部地区"],["cn","中国 / 港台"],["us","美国"],["eu","欧洲"],["jp","日本"],["kr","韩国"],["in","印度"]].map(([id,name])=><SelectItem key={id} value={id}>{name}</SelectItem>)}</SelectContent></Select></div>
    {error&&<p className="playback-message" role="alert"><CircleAlert size={18}/>{error}</p>}
    {busy&&!results.works.length?<CardSkeletons/>:shown.length?<div className={"media-grid"+(route.kind==="manga"?" manga-grid":"")}>{shown.map(w=><Card key={w.key} work={w} onOpen={openWork}/>)}</div>:<Empty title={region!=="all"?"这个地区暂无匹配作品":"暂未找到匹配作品"}  action={()=>navigate({view:"sources",q:route.q,kind:route.kind})} actionLabel="查看全部来源"/>}
    {(route.q||route.kind==="manga")&&results.works.length>0&&results.page<10&&<div className="load-more"><button className="secondary-button" disabled={busy} onClick={()=>void loadResults(route.q,route.kind,results.page+1,true)}>{busy?"正在读取…":"显示更多"}</button></div>}
   </div>}
  </div>
  
  </main>
  <nav className="mobile-bottom" aria-label="快捷导航">{[{id:"home",label:"主页",icon:House},{id:"search",label:"搜索",icon:Search},{id:"library",label:"资料库",icon:Library},{id:"sources",label:"来源",icon:Layers3}].map(({id,label,icon:Icon})=><button key={id} className={route.view===id?"active":""} onClick={()=>navigate({view:id as View,q:"",kind:"all"})}><Icon size={21}/><span>{label}</span></button>)}</nav>
 </div>;
}
function PageHeading({title}:{title:string}){return <div className="page-heading"><h1>{title}</h1></div>;}
function Empty({title,note,action,actionLabel}:{title:string;note?:string;action?:()=>void;actionLabel?:string}){return <div className="empty-result"><Library size={36}/><h3>{title}</h3>{note&&<p>{note}</p>}{action&&<button className="secondary-button" onClick={action}>{actionLabel}</button>}</div>;}
function Loading(){return <div className="loading-player" role="status"><LoaderCircle className="spinning"/>正在读取…</div>;}
function CardSkeletons(){return <div className="media-grid">{Array.from({length:6},(_,i)=><div key={i}><Skeleton className="card-skeleton"/><Skeleton className="title-skeleton"/></div>)}</div>;}
function Card({work:w,onOpen,progress}:{work:Work;onOpen:(w:Work)=>void;progress?:Progress}){return <button className={"work-card"+(w.kind==="manga"?" comic-card":"")} data-work-key={w.key} onClick={()=>onOpen(w)}><div className="card-art"><span className="poster-placeholder" aria-hidden="true">{w.title}</span>{w.poster&&<img src={w.poster} alt="" loading="lazy" decoding="async" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.style.opacity="0";}}/>}<span className="card-hover">{w.kind==="manga"?<BookOpen size={23}/>:<Play size={23} fill="currentColor"/>}</span>{(w.kind==="manga"?mangaSources(w).length:w.sources.length)>0&&<span className="source-badge">{w.kind==="manga"?mangaSources(w).length:w.sources.length}</span>}{progress&&<span className="watch-progress"><span style={{width:Math.min(100,progress.seconds/progress.duration*100)+"%"}}/></span>}</div><h3>{w.title}</h3>{!w.rank&&<p>{progress?Math.floor(progress.seconds/60)+" 分钟":(w.year?w.year+" · ":"")+kindNames[w.kind]}</p>}</button>;}
function Shelf({title,subtitle,works,onOpen,progress,loading,error,onMore}:{title:string;subtitle?:string;works:Work[];onOpen:(w:Work)=>void;progress?:Progress[];loading?:boolean;error?:string;onMore?:()=>void}){
 const row=useRef<HTMLDivElement>(null);
 return <section className="shelf-section"><div className="section-heading"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><div className="shelf-actions">{onMore&&<button className="text-button" onClick={onMore}>查看全部</button>}<button className="round-button small" aria-label={title+"，上一组"} onClick={()=>row.current?.scrollBy({left:-(row.current.clientWidth*.85),behavior:"smooth"})}><ChevronLeft size={20}/></button><button className="round-button small" aria-label={title+"，下一组"} onClick={()=>row.current?.scrollBy({left:row.current.clientWidth*.85,behavior:"smooth"})}><ChevronRight size={20}/></button></div></div><div className="shelf" ref={row} onKeyDown={e=>{if(e.key!=="ArrowRight"&&e.key!=="ArrowLeft")return;const cards=Array.from(row.current?.querySelectorAll<HTMLButtonElement>(".work-card")||[]);const i=cards.indexOf(document.activeElement as HTMLButtonElement);const next=cards[i+(e.key==="ArrowRight"?1:-1)];if(next){e.preventDefault();next.focus({preventScroll:true});next.scrollIntoView({behavior:"smooth",block:"nearest",inline:"nearest"});}}}>{loading&&!works.length?Array.from({length:3},(_,i)=><Skeleton key={i} className="shelf-skeleton"/>):works.map(w=><Card key={w.key} work={w} onOpen={onOpen} progress={progress?.find(p=>p.work.key===w.key)}/>)}</div>{!loading&&!works.length&&<p className="source-note">{error||"来源暂未返回作品，请稍后搜索片名。"}</p>}</section>;
}
function ExternalEntries({kind,query,compact=false}:{kind:string;query:string;compact?:boolean}){const entries=directory.filter(d=>kind==="all"||d.kind===kind||d.kind==="tool"||"kinds" in d&&(d.kinds as readonly string[]).includes(kind));const links=<div className="directory-grid">{entries.map(d=><a key={d.name} href={"search" in d&&query?d.search.replace("{query}",encodeURIComponent(query)):d.url} target="_blank" rel="noopener noreferrer"><div><strong>{d.name}</strong></div><ExternalLink size={17}/></a>)}</div>;return compact?<details className="external-section extra-sources"><summary>更多来源</summary>{links}</details>:<section className="external-section"><div className="section-heading"><h2>网站</h2></div>{links}</section>;}
function Detail({work,onBack,saved,onSave,resume}:{work:Work;onBack:()=>void;saved:boolean;onSave:()=>void;resume?:Progress}){
 const [resolved,setResolved]=useState(work),[provider,setProvider]=useState(work.sources.length?sourceKey(preferredSource(work.sources,resume?.provider)):""),[source,setSource]=useState<Source|null>(null),[route,setRoute]=useState("0"),[episode,setEpisode]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[sourceOpen,setSourceOpen]=useState(false),[playing,setPlaying]=useState(false);
 const stage=useRef<HTMLDivElement>(null),hasResumed=useRef(false);
 const [qualityInfo,setQualityInfo]=useState<Record<string,number>>({});
 useEffect(()=>{if(!sourceOpen)return;const abort=new AbortController();void Promise.allSettled(resolved.sources.map(async s=>{const r=await fetch("/api/quality?"+new URLSearchParams({provider:s.provider,id:s.id}),{signal:abort.signal});const d=await r.json() as {qualityMax?:number};if(!abort.signal.aborted&&d.qualityMax)setQualityInfo(v=>({...v,[sourceKey(s)]:d.qualityMax!}));}));return()=>abort.abort();},[sourceOpen,resolved.sources]);
 useEffect(()=>{if(work.kind==="manga"){setLoading(false);return;}if(work.sources.length){setResolved(work);setProvider(sourceKey(preferredSource(work.sources,resume?.provider)));return;}const abort=new AbortController();setLoading(true);fetch("/api/search?q="+encodeURIComponent(work.title)+"&kind="+work.kind,{signal:abort.signal}).then(r=>r.json() as Promise<any>).then(d=>{const w=d.works?.find((w:Work)=>w.year===work.year&&w.title===work.title)||d.works?.find((w:Work)=>w.title===work.title);if(!w?.sources.length)throw new Error("暂时没有可用分流，请稍后再试。");setResolved({...work,...w});setProvider(sourceKey(preferredSource(w.sources,resume?.provider)));}).catch(e=>{if(e.name!=="AbortError"){setError(e.message);setLoading(false);}});return()=>abort.abort();},[work.key]);
 useEffect(()=>{const s=resolved.sources.find(s=>sourceKey(s)===provider);if(!s)return;const abort=new AbortController();setSource(null);setLoading(true);setError("");setRoute("0");setEpisode(0);
  fetch("/api/detail?provider="+s.provider+"&id="+s.id,{signal:abort.signal}).then(r=>r.json() as Promise<any>).then(d=>{if(d.error)throw new Error(d.error);const found=d.sources?.[0] as Source|undefined;if(!found)throw new Error("此分流暂不可用");setSource(found);if(resume&&!hasResumed.current){let match=false;found.routes.forEach((r,ri)=>{const ei=r.episodes.findIndex(e=>e.url===resume.episodeUrl);if(ei>=0){setRoute(String(ri));setEpisode(ei);match=true;}});if(match)hasResumed.current=true;}}).catch(e=>{if(e.name!=="AbortError")setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();
 },[provider,resolved]);
 const routes=source?.routes||[],current=routes[Number(route)],ep=current?.episodes[episode];
 function begin(){setPlaying(true);setTimeout(()=>stage.current?.scrollIntoView({behavior:"smooth",block:"start"}),60);}
 return <article className="detail-view"><section className={"hero detail-hero"+(work.kind==="manga"?" manga-hero":"")}><img className="hero-image" src={artwork(work)} alt="" referrerPolicy="no-referrer"/><div className="hero-shade"/><button className="detail-back round-button glass" aria-label="返回上一页" onClick={onBack}><ChevronLeft/></button><div className="hero-copy"><div className="hero-eyebrow">{kindNames[work.kind]}</div><h1>{work.title}</h1><div className="hero-meta"><span>{work.year}</span><span>{({ja:"日本",ko:"韩国",zh:"中国",en:"英语地区"} as Record<string,string>)[work.area]||work.area}</span>{work.kind!=="manga"&&<span>{work.language}</span>}</div><div className="hero-actions"><button className="primary-button" onClick={begin}>{work.kind==="manga"?<BookOpen size={19}/>:<Play size={18} fill="currentColor"/>}{work.kind==="manga"?"开始阅读":resume?"继续观看":"开始观看"}</button><button className="round-button glass" aria-label={saved?"移出待看":"加入待看"} aria-pressed={saved} onClick={onSave}>{saved?<Check/>:<Plus/>}</button>{work.kind!=="manga"&&<button className="secondary-button glass" onClick={()=>setSourceOpen(true)}><Layers3 size={18}/>{resolved.sources.length?"选择分流 · "+resolved.sources.length:"查找分流"}</button>}</div>{resume&&work.kind!=="manga"&&<span className="resume-note">上次看到 {Math.floor(resume.seconds/60)} 分钟 · {resume.episodeLabel}</span>}</div></section>
 <div className="detail-body">
 {work.kind==="manga"?<div ref={stage} className="playback-stage"><MangaReader work={work}/></div>:<>
  <Dialog open={sourceOpen} onOpenChange={setSourceOpen}><DialogContent className="source-dialog" aria-describedby={undefined}><DialogHeader><DialogTitle>选择分流</DialogTitle></DialogHeader><div className="source-options">{resolved.sources.map(s=><button className={sourceKey(s)===provider?"selected":""} key={s.provider+s.id} onClick={()=>{setProvider(sourceKey(s));setSourceOpen(false);}}><span className="source-symbol"><Layers3 size={22}/></span><span><strong>{s.providerName}</strong><small>最高 {qualityText(qualityInfo[sourceKey(s)]||s.qualityMax,s.qualityHint)}</small></span>{sourceKey(s)===provider&&<Check size={21}/>}</button>)}</div>{!resolved.sources.length&&(loading?<Loading/>:<p role="status">{error||"没有找到可用分流"}</p>)}</DialogContent></Dialog>
  <div ref={stage} className={"playback-stage"+(!playing?" stage-collapsed":"")}>
   {playing&&(loading?<Loading/>:error?<div className="empty-result"><CircleAlert/><h3>这个分流暂时无法打开</h3><p>{error}</p><button className="secondary-button" onClick={()=>setSourceOpen(true)}>切换分流</button></div>:ep?<MediaPlayer episode={ep} title={work.title} poster={artwork(work)} onQuality={max=>setQualityInfo(v=>v[provider]>=max?v:{...v,[provider]:max})} autoPlay initialTime={resume?.episodeUrl===ep.url?resume.seconds:0} onProgress={(seconds,duration)=>saveProgress({work:resolved,seconds,duration,episodeLabel:ep.label,episodeUrl:ep.url,provider,updated:Date.now()})} onNext={episode<current.episodes.length-1?()=>setEpisode(e=>e+1):undefined}/>:<Empty title="暂无兼容的播放线路" note="尝试其他分流。" action={()=>setSourceOpen(true)} actionLabel="切换分流"/>)}
  </div>
  <section className="episode-section"><div className="section-heading"><div><h2>{work.kind==="movie"?"观看选项":"剧集"}</h2>{source&&<p>{source.providerName}</p>}</div><button className="secondary-button" onClick={()=>setSourceOpen(true)}><Layers3 size={17}/>切换分流</button></div>{loading?<p className="loading-text"><LoaderCircle className="spinning" size={17}/>正在读取播放列表…</p>:error?<p className="source-note">{error}</p>:<>{routes.length>1&&<Select value={route} onValueChange={r=>{setRoute(r);setEpisode(0);}}><SelectTrigger aria-label="播放线路"><SelectValue/></SelectTrigger><SelectContent>{routes.map((r,i)=><SelectItem value={String(i)} key={i}>{r.name} · {r.episodes.length} 集</SelectItem>)}</SelectContent></Select>}<div className="episode-list">{current?.episodes.map((e,i)=><button key={e.url+i} className={playing&&episode===i?"selected":""} onClick={()=>{setEpisode(i);begin();}}><Play size={16}/><span>{e.label}</span></button>)}</div></>}</section>
 </>}
 <section className="about-section"><h2>关于《{work.title}》</h2><div className="about-grid"><div><h3>故事简介</h3><p>{work.description||"暂无简介。"}</p></div><div><h3>作品信息</h3>{work.director&&<p>导演 · {work.director}</p>}{work.actor&&<p>{work.kind==="manga"?"作者":"主演"} · {work.actor}</p>}<p>{work.year} · {kindNames[work.kind]}</p></div></div></section>
 <ExternalEntries kind={work.kind} query={work.title} compact/>
 </div></article>;
}
function qualityText(height:number|undefined,hint:string){if(height)return height>=2160?"4K":height+"p";const value=hint?.match(/4k|2160p|1080p|720p|480p/i)?.[0];return value?value.toUpperCase():"未知";}

function HeroCarousel({works,onOpen,saved,onSave}:{works:Work[];onOpen:(w:Work)=>void;saved:Work[];onSave:(w:Work)=>void}){
 const [index,setIndex]=useState(0),[hold,setHold]=useState(false),[running,setRunning]=useState(true),[reduced,setReduced]=useState(false);
 const list=works.slice(0,6),count=list.length,current=list[index%Math.max(1,count)];
 useEffect(()=>{const m=matchMedia("(prefers-reduced-motion: reduce)");const update=()=>setReduced(m.matches);update();m.addEventListener("change",update);return()=>m.removeEventListener("change",update);},[]);
 useEffect(()=>{if(hold||!running||reduced||count<2)return;const id=setInterval(()=>{if(!document.hidden)setIndex(i=>(i+1)%count);},6500);return()=>clearInterval(id);},[hold,running,reduced,count]);
 if(!current)return <section className="hero home-hero"><div className="hero-copy"><h1>热播</h1></div></section>;
 const isSaved=saved.some(w=>w.key===current.key);
 return <section className="hero home-hero hero-carousel" aria-label="热播推荐" aria-roledescription="轮播" onMouseEnter={()=>setHold(true)} onMouseLeave={()=>setHold(false)} onFocus={()=>setHold(true)} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setHold(false);}}>
  {list.map((w,i)=><img key={w.key} className={"hero-image carousel-image"+(i===index%count?" active":"")} src={w.backdrop} alt="" fetchPriority={i===0?"high":"auto"} loading={i<2?"eager":"lazy"}/>)}
  <div className="hero-shade"/>
  <div className="hero-copy carousel-copy" key={current.key}><div className="hero-eyebrow">{kindNames[current.kind]}</div><h1>{current.title}</h1><div className="hero-actions"><button className="primary-button" onClick={()=>onOpen(current)}><Play size={18} fill="currentColor"/>观看</button><button className="round-button glass" aria-label={isSaved?"移出待看":"加入待看"} aria-pressed={isSaved} onClick={()=>onSave(current)}>{isSaved?<Check/>:<Plus/>}</button></div></div>
  <div className="hero-pagination"><button className="round-button small glass" aria-label="上一张海报" onClick={()=>setIndex(i=>(i-1+count)%count)}><ChevronLeft size={18}/></button><div className="hero-dots">{list.map((w,i)=><button key={w.key} className={i===index%count?"active":""} aria-label={"切换到"+w.title} aria-pressed={i===index%count} onClick={()=>setIndex(i)}><span/></button>)}</div><button className="round-button small glass" aria-label="下一张海报" onClick={()=>setIndex(i=>(i+1)%count)}><ChevronRight size={18}/></button><button className="carousel-pause" aria-label={running?"暂停轮播":"自动轮播"} onClick={()=>setRunning(!running)}>{running?<span className="pause-glyph"/>:<Play size={12} fill="currentColor"/>}</button></div>
 </section>;
}






