export const directory = [
 {name:"4K影院",url:"https://www.4kcz.com/",kind:"movie",kinds:["movie","tv","anime"],note:""},
 {name:"次元城",url:"https://www.cycani.org/",kind:"anime",note:""},
 {name:"girigiri",url:"https://ani.girigirilove.com/",kind:"anime",note:""},
 {name:"低端影视",url:"https://ddys.one/",search:"https://ddys.one/?s={query}&post_type=post",kind:"movie",kinds:["movie","tv","anime"],note:""},
 {name:"茶杯狐",url:"https://cupfox.love/",kind:"movie",kinds:["movie","tv","anime"],note:""},
 {name:"樱之空",url:"https://www.skr1.cc/",search:"https://www.skr1.cc/vodsearch/-------------/?wd={query}",kind:"anime",note:""},
 {name:"FMHY 影视目录",url:"https://fmhy.net/video",kind:"movie",note:"全球电影、剧集来源目录"},
 {name:"FMHY 华语目录",url:"https://fmhy.net/non-english#chinese-华语",kind:"tv",note:"华语与中文字幕来源"},
 {name:"MoMoVOD",url:"https://momovod.app/",kind:"movie",note:"电影、剧集、动画；访问可能受限"},
 {name:"VidHub",url:"https://vidhub2.top/",kind:"movie",note:"电影、剧集、动画；访问可能受限"},
 {name:"华策影视",url:"https://www.youtube.com/@Huace/playlists",kind:"tv",note:"中国剧集；平台可能插入广告"},
 {name:"韩国影像资料院",url:"https://www.youtube.com/@KoreanFilm/playlists",kind:"movie",note:"韩国经典电影；中文需逐片核对"},
 {name:"KBS WORLD",url:"https://www.youtube.com/@KBSWORLDTV/playlists",kind:"tv",note:"韩国剧集与单集剧"},
 {name:"Shemaroo Movies",url:"https://www.youtube.com/@ShemarooMovies/playlists",kind:"movie",note:"印度电影；平台可能插入广告"},
 {name:"Rajshri",url:"https://www.youtube.com/@Rajshri/playlists",kind:"movie",note:"印度电影；字幕与版本待核对"},
 {name:"FMHY 动画目录",url:"https://fmhy.net/video#anime-streaming",kind:"anime",note:"多地区动画来源"},
 {name:"Anime1",url:"https://anime1.me/",search:"https://anime1.me/?s={query}",kind:"anime",note:"中文动画；外部播放器"},
 {name:"AGE 动漫",url:"https://www.agedm.io/",search:"https://www.agedm.io/search?query={query}",kind:"anime",note:"动画搜索；外部播放器"},
 {name:"木棉花 TW",url:"https://www.youtube.com/@MuseTW/videos",kind:"anime",note:"繁中动画；地区与期限限制"},
 {name:"Ani-One 中文",url:"https://www.youtube.com/@AniOneAnime/videos",kind:"anime",note:"繁中动画；免费与会员作品并存"},
 {name:"FMHY 漫画目录",url:"https://fmhy.net/reading#manga",kind:"manga",note:"日漫、韩漫、国漫来源目录"},
 {name:"漫画柜",url:"https://www.manhuagui.com/",search:"https://www.manhuagui.com/s/{query}.html",kind:"manga",note:"中文漫画；外部阅读可能有广告"},
 {name:"Komiic",url:"https://komiic.com/",search:"https://komiic.com/search/{query}",kind:"manga",note:""},
 {name:"拷贝漫画",url:"https://mangacopy.com/",search:"https://mangacopy.com/search?q={query}&q_type=",kind:"manga",note:""},
 {name:"MangaDex",url:"https://mangadex.org/",kind:"manga",note:"已接入站内搜索、章节与原图阅读"},
 {name:"WEBTOON 繁中",url:"https://www.webtoons.com/zh-hant/",search:"https://www.webtoons.com/zh-hant/search?keyword={query}",kind:"manga",note:"公开章节；部分章节收费"},
 {name:"MANGA Plus",url:"https://mangaplus.shueisha.co.jp/",kind:"manga",note:"部分公开章节；无中文"},
 {name:"Movie-Censorship",url:"https://www.movie-censorship.com/",search:"https://www.movie-censorship.com/list.php?s={query}",kind:"tool",note:"不同发行版本与删改比较"},
 {name:"射手字幕",url:"https://assrt.net/",search:"https://assrt.net/sub/?searchword={query}",kind:"tool",note:"查找外挂中文字幕"},
 {name:"FMHY 字幕目录",url:"https://fmhy.net/video#download-subtitles",kind:"tool",note:"外挂字幕来源目录"},
 {name:"ARTE 欧洲电影",url:"https://www.arte.tv/en/videos/cinema/",kind:"movie",note:"欧洲电影；字幕与地区限制待核对"},
 {name:"Mosfilm 字幕电影",url:"https://www.youtube.com/channel/UCm5U4zqpahzyNXBv5ZT51Jw",kind:"movie",note:"欧洲经典电影；平台可能插入广告"},
 {name:"mpv",url:"https://mpv.io/",kind:"tool",note:"本地视频播放器"},
 {name:"VLC",url:"https://www.videolan.org/vlc/",kind:"tool",note:"本地视频播放器"},
 {name:"SumatraPDF",url:"https://www.sumatrapdfreader.org/free-pdf-reader",kind:"tool",note:"本地漫画与 PDF 阅读器"},
 {name:"LibreTV",url:"https://github.com/LibreSpark/LibreTV",kind:"tool",note:"其他自建聚合播放方案"},
] as const;
